### ISSUE TITLE
gee not available anymore

### ISSUE THREAD

**Issue by avioli** [technosophos/ValaXdebugTools#1]
Gee is not available as is under homebrew.

There are libgee (v0.16.0) and libgee08 (v0.8) and just installing them doesn't help.

Any ideas?

**Comment by technosophos** [comment]
It should be libgee, which provides `Gee`. I'm not sure if you'd have to tweak the environment for the build script when installing from Homebrew.

**Comment by robinmitra** [comment]
Yeah would probably need tweaking the environment, as the build is failing. I spent an hour trying to figure it but no luck since I don't have any experience of Vala. Do you mind looking into this?

**Comment by technosophos** [comment]
Apparently the Gee lib went from 1.0 to 0.8. I'd like to hear the story behind that version numbering change.

So, I did the following:
- Rewrote `build.sh` as a standard `Makefile`
- Changed the README to correctly indicate the dependencies
- Made a small modification to the library to properly sort

Note that Vala has undergone some changes, and the build _will_ emit warnings. But it should compile and function correctly.
